title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

wlk<-read.csv('activity.csv')

## What is mean total number of steps taken per day?

Histogram of the total number of steps taken each day

wlkDay<-aggregate(steps~date,wlk, sum, na.rm=T)
hist(wlkDay$steps, main='Total # of Steps Per Day', xlab='# of Steps')

Mean and median number of steps taken each day

wlkMean<-mean(wlkDay$steps)
wlkMedian<-median(wlkDay$steps)

## What is the average daily activity pattern?

Time series plot of the average number of steps taken

wlkTS<-aggregate(steps~interval, wlk, mean, na.rm=T)
plot(wlkTS, main='Time Series by Avg. number of steps', pch=16)
lines(wlkTS)

The 5-minute interval that, on average, contains the maximum number of steps

wlkTSMax<-wlkTS[which.max(wlkTS$steps),]


## Imputing missing values

Code to describe and show a strategy for imputing missing data

wlkNA<-is.na(wlk$steps) ##Identify missing values (NA)
wlktotNA<-sum(wlkNA) ##Count the NA values
print(wlktotNA)

Replace missing interval with the mean of the 5-min interval

wlk0<-read.csv('activity.csv')
wlk0$steps[is.na(wlk0$steps)]=wlkTS$steps

Histogram of the total number of steps taken each day after missing values are imputed

wlk0Day<-aggregate(steps~date,wlk0, sum)
hist(wlk0Day$steps, main='Total # of Steps Per Day (Non-NA)', xlab='# of Steps')


## Are there differences in activity patterns between weekdays and weekends?

Panel plot comparing the average number of steps taken per 5-minute interval across weekdays and weekends

library(chron)
wlk$we=chron::is.weekend(wlk$date) ##TRUE is a weekend / FALSE is a weekday
wlkWE<-subset(wlk, wlk$we==TRUE)
wlkWD<-subset(wlk, wlk$we==FALSE)

wlkWEDay<-aggregate(steps~date, wlkWE,mean)
wlkWDDay<-aggregate(steps~date, wlkWD,mean)

par(mfrow=c(1,2), mar=c(4,4,2,1))
hist(wlkWDDay$steps, main='Weekday', xlab='Avg. # of Steps',col="blue", 
     ylim=c(0,12))
hist(wlkWEDay$steps, main='Weekend Day ', xlab='Avg. # of Steps',col="red", 
     ylim=c(0,12))
